use percolator::*;
use core::mem::offset_of;

fn main() {
    println!("=== ACCOUNT FIELDS ===");
    println!("capital:{}", offset_of!(Account, capital));
    println!("kind:{}", offset_of!(Account, kind));
    println!("pnl:{}", offset_of!(Account, pnl));
    println!("reserved_pnl:{}", offset_of!(Account, reserved_pnl));
    println!("position_basis_q:{}", offset_of!(Account, position_basis_q));
    println!("adl_a_basis:{}", offset_of!(Account, adl_a_basis));
    println!("adl_k_snap:{}", offset_of!(Account, adl_k_snap));
    println!("f_snap:{}", offset_of!(Account, f_snap));
    println!("adl_epoch_snap:{}", offset_of!(Account, adl_epoch_snap));
    println!("matcher_program:{}", offset_of!(Account, matcher_program));
    println!("matcher_context:{}", offset_of!(Account, matcher_context));
    println!("owner:{}", offset_of!(Account, owner));
    println!("fee_credits:{}", offset_of!(Account, fee_credits));
    println!("sched_present:{}", offset_of!(Account, sched_present));
    println!("sched_remaining_q:{}", offset_of!(Account, sched_remaining_q));
    println!("sched_anchor_q:{}", offset_of!(Account, sched_anchor_q));
    println!("sched_start_slot:{}", offset_of!(Account, sched_start_slot));
    println!("sched_horizon:{}", offset_of!(Account, sched_horizon));
    println!("sched_release_q:{}", offset_of!(Account, sched_release_q));
    println!("pending_present:{}", offset_of!(Account, pending_present));
    println!("pending_remaining_q:{}", offset_of!(Account, pending_remaining_q));
    println!("pending_horizon:{}", offset_of!(Account, pending_horizon));
    println!("pending_created_slot:{}", offset_of!(Account, pending_created_slot));

    println!("\n=== RISKENGINE FIELDS ===");
    println!("vault:{}", offset_of!(RiskEngine, vault));
    println!("insurance_fund:{}", offset_of!(RiskEngine, insurance_fund));
    println!("params:{}", offset_of!(RiskEngine, params));
    println!("current_slot:{}", offset_of!(RiskEngine, current_slot));
    println!("market_mode:{}", offset_of!(RiskEngine, market_mode));
    println!("resolved_price:{}", offset_of!(RiskEngine, resolved_price));
    println!("resolved_slot:{}", offset_of!(RiskEngine, resolved_slot));
    println!("resolved_payout_h_num:{}", offset_of!(RiskEngine, resolved_payout_h_num));
    println!("resolved_payout_h_den:{}", offset_of!(RiskEngine, resolved_payout_h_den));
    println!("resolved_payout_ready:{}", offset_of!(RiskEngine, resolved_payout_ready));
    println!("resolved_k_long_terminal_delta:{}", offset_of!(RiskEngine, resolved_k_long_terminal_delta));
    println!("resolved_k_short_terminal_delta:{}", offset_of!(RiskEngine, resolved_k_short_terminal_delta));
    println!("resolved_live_price:{}", offset_of!(RiskEngine, resolved_live_price));
    // last_crank_slot was renamed → see last_market_slot lower in this file.
    // gc_cursor was retired in v12.1 (84a9293 "Simplify ADL: replace windowed crank with full-scan").
    println!("c_tot:{}", offset_of!(RiskEngine, c_tot));
    println!("pnl_pos_tot:{}", offset_of!(RiskEngine, pnl_pos_tot));
    println!("pnl_matured_pos_tot:{}", offset_of!(RiskEngine, pnl_matured_pos_tot));
    println!("adl_mult_long:{}", offset_of!(RiskEngine, adl_mult_long));
    println!("adl_mult_short:{}", offset_of!(RiskEngine, adl_mult_short));
    println!("adl_coeff_long:{}", offset_of!(RiskEngine, adl_coeff_long));
    println!("adl_coeff_short:{}", offset_of!(RiskEngine, adl_coeff_short));
    println!("adl_epoch_long:{}", offset_of!(RiskEngine, adl_epoch_long));
    println!("adl_epoch_short:{}", offset_of!(RiskEngine, adl_epoch_short));
    println!("adl_epoch_start_k_long:{}", offset_of!(RiskEngine, adl_epoch_start_k_long));
    println!("adl_epoch_start_k_short:{}", offset_of!(RiskEngine, adl_epoch_start_k_short));
    println!("oi_eff_long_q:{}", offset_of!(RiskEngine, oi_eff_long_q));
    println!("oi_eff_short_q:{}", offset_of!(RiskEngine, oi_eff_short_q));
    println!("side_mode_long:{}", offset_of!(RiskEngine, side_mode_long));
    println!("side_mode_short:{}", offset_of!(RiskEngine, side_mode_short));
    println!("stored_pos_count_long:{}", offset_of!(RiskEngine, stored_pos_count_long));
    println!("stored_pos_count_short:{}", offset_of!(RiskEngine, stored_pos_count_short));
    println!("stale_account_count_long:{}", offset_of!(RiskEngine, stale_account_count_long));
    println!("stale_account_count_short:{}", offset_of!(RiskEngine, stale_account_count_short));
    println!("phantom_dust_bound_long_q:{}", offset_of!(RiskEngine, phantom_dust_bound_long_q));
    println!("phantom_dust_bound_short_q:{}", offset_of!(RiskEngine, phantom_dust_bound_short_q));
    println!("materialized_account_count:{}", offset_of!(RiskEngine, materialized_account_count));
    println!("neg_pnl_account_count:{}", offset_of!(RiskEngine, neg_pnl_account_count));
    println!("last_oracle_price:{}", offset_of!(RiskEngine, last_oracle_price));
    println!("fund_px_last:{}", offset_of!(RiskEngine, fund_px_last));
    println!("last_market_slot:{}", offset_of!(RiskEngine, last_market_slot));
    println!("f_long_num:{}", offset_of!(RiskEngine, f_long_num));
    println!("f_short_num:{}", offset_of!(RiskEngine, f_short_num));
    println!("f_epoch_start_long_num:{}", offset_of!(RiskEngine, f_epoch_start_long_num));
    println!("f_epoch_start_short_num:{}", offset_of!(RiskEngine, f_epoch_start_short_num));
    println!("used:{}", offset_of!(RiskEngine, used));
    println!("num_used_accounts:{}", offset_of!(RiskEngine, num_used_accounts));
    println!("free_head:{}", offset_of!(RiskEngine, free_head));
    println!("next_free:{}", offset_of!(RiskEngine, next_free));
    println!("accounts:{}", offset_of!(RiskEngine, accounts));
}
